const myarr = ["sapana","sapana","nagar"]
console.log(myarr)
const myar = new Array(1,2,3,4)
console.log(myar[1])
myar.push(6)
console.log(myar)
myar.pop()
console.log(myar)
myar.unshift(4)
console.log(myar)
myar.shift()
console.log(myar)
console.log(myar.includes(4))
console.log(myar.indexOf(3))
const  newarr = myar.join()
console.log(newarr)

console.log(typeof newarr)
console.log("a",myar)
const my1 = myar.slice(1,3)
console.log("B",my1)
console.log("C",myar)
const my2 = myar.splice(1,3)
console.log("D",my2)

console.log("E",myar)