//tc39
 let myDate = new Date()
 console.log(myDate)
 console.log(myDate.toDateString())
 console.log(myDate.toLocaleString())
 console.log(typeof myDate)
 let create = new Date ("01-12-2024")
 console.log(create)
 let today =  Date.now()
 console.log(today)
 console.log(create.getTime())
 console.log(Math.floor(Date.now()/1000))
 let newDate = new Date()
 console.log(newDate.getMonth())
 console.log(newDate.toLocaleString('default',{weekday:"long"}))
